//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCR_DLL_Invoker
{
    using System;
    using System.Collections.Generic;
    
    public partial class APICallHistory
    {
        public long ID { get; set; }
        public string Comment { get; set; }
        public string Status { get; set; }
        public Nullable<long> RunID { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
    }
}
