//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCR_DLL_Invoker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APICallHistory> APICallHistories { get; set; }
        public virtual DbSet<ExceptionLog> ExceptionLogs { get; set; }
        public virtual DbSet<MasterFormApplicationSummary> MasterFormApplicationSummaries { get; set; }
    
        public virtual ObjectResult<Nullable<long>> GetNewRunID()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("GetNewRunID");
        }
    
        public virtual ObjectResult<proc_APICallHistory_GetLastRecord_Result> APICallHistory_GetLastRecord()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_APICallHistory_GetLastRecord_Result>("APICallHistory_GetLastRecord");
        }
    }
}
